[front_matter]
yaml = true
toml = false
json = false

used_for_html = true
used_for_text = false

[sm_card]
enabled = false

[sm_card.default]
#image = ""
#use_xcom_large = false
#description = "Example Web Site"
#site_name = "Example, Inc."
#site_xcom_id = "@name"
#creator_xcom_id = "@name"

[print_paper]
mapping = "/conf/etc/print_paper_mapping.conf"

#[print_paper.default]
#paper_type = ""
#print_zoom = 1.0

#[[link_menu.default]]
#label = "Top"
#url = "/file/"
