socket_type = ""
socket_path = ""
cache_control = "max-age=1, must-revalidate"

url_top_path = "/file/"
url_lib_path = "/"

document_root = "/file/"
index_name = "README.md"

icon_path = "/conf/lib/icon"

tmpl_paths = [
  "/conf/lib/tmpl/*.tmpl",
  "/conf/lib/app_tmpl/mdview.tmpl",
]

main_tmpl = "mdview.tmpl"
#page_style = "default"

#markdown_ext = []
markdown_config  = "/conf/etc/markdown.conf"
custom_page_config = "/conf/etc/custom_page.conf"

theme_style = "radio"
#theme_style = "os"

directory_view_mode = "auto"
directory_view_roots = [
	"/file/",
]
directory_view_path_hidden = [
	'^/conf/',
]
directory_view_hidden = [
	'^\.',
]
