default = ""
auto = "auto"
A3 = "A3"
A3L = "A3 landscape"
A4 = "A4"
A4L = "A4 landscape"
A5 = "A5"
A5L = "A5 landscape"
A6 = "105mm 148mm"
A6L = "148mm 105mm"
B4 = "JIS-B4"
B4L = "JIS-B4 landscape"
B5 = "JIS-B5"
B5L = "JIS-B5 landscape"
B6 = "128mm 182mm"
B6L = "182mm 128mm"
letter = "letter"
letterL = "letter landscape"
ledger = "ledger"
ledgerL = "ledger landscape"
hagaki = "100mm 148mm"
hagakiL = "148mm 100mm"
